services:
  db:
    image: postgres:16.0-alpine
    container_name: c-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3

  django:
    build: ./log_aggregator
    container_name: c-django
    volumes:
      - django_media:/var/www/media
      - django_static:/var/www/static
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: c-nginx
    volumes:
      - ./infra/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - django_media:/var/www/media
      - django_static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      django:
        condition: service_healthy


volumes:
  postgres_data:
  django_media:
  django_static: