# Generated by Django 5.1 on 2024-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NginxLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_ip", models.GenericIPAddressField()),
                ("time", models.DateTimeField()),
                ("http_method", models.CharField(max_length=10)),
                ("uri", models.CharField(max_length=255)),
                ("response_code", models.IntegerField()),
                ("response_size", models.BigIntegerField()),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("referrer", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["remote_ip"], name="logs_nginxl_remote__ae6f82_idx"
                    ),
                    models.Index(fields=["time"], name="logs_nginxl_time_7c8681_idx"),
                    models.Index(
                        fields=["http_method"], name="logs_nginxl_http_me_4c65aa_idx"
                    ),
                    models.Index(fields=["uri"], name="logs_nginxl_uri_1f8de5_idx"),
                    models.Index(
                        fields=["response_code"], name="logs_nginxl_respons_3d7e91_idx"
                    ),
                ],
            },
        ),
    ]
